<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cs_templates"
 *
 * Auto generated by Extension Builder 2013-09-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[clickstorm] GDPR powermail checkbox',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Marc Hirdes',
    'author_email' => 'hirdes@clickstorm.de',
    'author_company' => 'clickstorm GmbH',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '2.0.1-de',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'powermail' => '8.1.0-8.99.99',
            'vhs' => '4.0.0-6.99.99'
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];